// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audit.proto

package com.gridcsp.adelson.sdk.audit.protobuf.v1;

public interface AuditRequestByIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:audit.v1.AuditRequestById)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * mongodb unique id of the record
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * mongodb unique id of the record
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
