// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audit.proto

package com.gridcsp.adelson.sdk.audit.protobuf.v1;

public final class AuditProto {
  private AuditProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_audit_v1_AuditRequestById_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_audit_v1_AuditRequestById_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_audit_v1_AuditRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_audit_v1_AuditRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_audit_v1_AuditLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_audit_v1_AuditLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_audit_v1_Filters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_audit_v1_Filters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_audit_v1_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_audit_v1_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_audit_v1_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_audit_v1_SearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013audit.proto\022\010audit.v1\032\031google/protobuf" +
      "/any.proto\032\037google/protobuf/timestamp.pr" +
      "oto\"\036\n\020AuditRequestById\022\n\n\002id\030\001 \001(\t\"\345\001\n\013" +
      "AuditRecord\022\n\n\002id\030\001 \001(\t\022\017\n\007subject\030\002 \001(\t" +
      "\022\017\n\007machine\030\003 \001(\t\022.\n\nevent_time\030\004 \001(\0132\032." +
      "google.protobuf.Timestamp\022\022\n\nevent_type\030" +
      "\005 \001(\t\022\020\n\010category\030\006 \001(\t\022\026\n\016correlation_i" +
      "d\030\007 \001(\t\022\023\n\013description\030\010 \001(\t\022%\n\007payload\030" +
      "\n \001(\0132\024.google.protobuf.Any\"\335\001\n\017AuditLog" +
      "Request\022\017\n\007subject\030\002 \001(\t\022\017\n\007machine\030\003 \001(" +
      "\t\022.\n\nevent_time\030\004 \001(\0132\032.google.protobuf." +
      "Timestamp\022\022\n\nevent_type\030\005 \001(\t\022\020\n\010categor" +
      "y\030\006 \001(\t\022\026\n\016correlation_id\030\007 \001(\t\022\023\n\013descr" +
      "iption\030\010 \001(\t\022%\n\007payload\030\n \001(\0132\024.google.p" +
      "rotobuf.Any\"\234\001\n\007Filters\022\017\n\007subject\030\001 \001(\t" +
      "\022\022\n\nevent_type\030\002 \001(\t\022.\n\nstart_date\030\003 \001(\013" +
      "2\032.google.protobuf.Timestamp\022,\n\010end_date" +
      "\030\004 \001(\0132\032.google.protobuf.Timestamp\022\016\n\006so" +
      "urce\030\005 \001(\t\"k\n\rSearchRequest\022!\n\006filter\030\001 " +
      "\001(\0132\021.audit.v1.Filters\022\021\n\tpage_size\030\002 \001(" +
      "\005\022\020\n\010order_by\030\003 \001(\t\022\022\n\npage_token\030\004 \001(\t\"" +
      "W\n\016SearchResponse\022,\n\raudit_records\030\001 \003(\013" +
      "2\025.audit.v1.AuditRecord\022\027\n\017next_page_tok" +
      "en\030\002 \001(\t2\340\001\n\014AuditService\022C\n\016getAuditRec" +
      "ord\022\032.audit.v1.AuditRequestById\032\025.audit." +
      "v1.AuditRecord\022B\n\016addAuditRecord\022\031.audit" +
      ".v1.AuditLogRequest\032\025.audit.v1.AuditReco" +
      "rd\022G\n\022searchAuditRecords\022\027.audit.v1.Sear" +
      "chRequest\032\030.audit.v1.SearchResponseB9\n)c" +
      "om.gridcsp.adelson.sdk.audit.protobuf.v1" +
      "B\nAuditProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_audit_v1_AuditRequestById_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_audit_v1_AuditRequestById_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_audit_v1_AuditRequestById_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_audit_v1_AuditRecord_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_audit_v1_AuditRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_audit_v1_AuditRecord_descriptor,
        new java.lang.String[] { "Id", "Subject", "Machine", "EventTime", "EventType", "Category", "CorrelationId", "Description", "Payload", });
    internal_static_audit_v1_AuditLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_audit_v1_AuditLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_audit_v1_AuditLogRequest_descriptor,
        new java.lang.String[] { "Subject", "Machine", "EventTime", "EventType", "Category", "CorrelationId", "Description", "Payload", });
    internal_static_audit_v1_Filters_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_audit_v1_Filters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_audit_v1_Filters_descriptor,
        new java.lang.String[] { "Subject", "EventType", "StartDate", "EndDate", "Source", });
    internal_static_audit_v1_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_audit_v1_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_audit_v1_SearchRequest_descriptor,
        new java.lang.String[] { "Filter", "PageSize", "OrderBy", "PageToken", });
    internal_static_audit_v1_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_audit_v1_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_audit_v1_SearchResponse_descriptor,
        new java.lang.String[] { "AuditRecords", "NextPageToken", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
