// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audit.proto

package com.gridcsp.adelson.sdk.audit.protobuf.v1;

/**
 * Protobuf type {@code audit.v1.Filters}
 */
public final class Filters extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:audit.v1.Filters)
    FiltersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Filters.newBuilder() to construct.
  private Filters(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Filters() {
    subject_ = "";
    eventType_ = "";
    source_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Filters();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Filters(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            subject_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            eventType_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (startDate_ != null) {
              subBuilder = startDate_.toBuilder();
            }
            startDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startDate_);
              startDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (endDate_ != null) {
              subBuilder = endDate_.toBuilder();
            }
            endDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endDate_);
              endDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            source_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gridcsp.adelson.sdk.audit.protobuf.v1.AuditProto.internal_static_audit_v1_Filters_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gridcsp.adelson.sdk.audit.protobuf.v1.AuditProto.internal_static_audit_v1_Filters_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters.class, com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters.Builder.class);
  }

  public static final int SUBJECT_FIELD_NUMBER = 1;
  private volatile java.lang.Object subject_;
  /**
   * <pre>
   * The subject (user or service) who did an action in the system
   * </pre>
   *
   * <code>string subject = 1;</code>
   * @return The subject.
   */
  @java.lang.Override
  public java.lang.String getSubject() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subject_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The subject (user or service) who did an action in the system
   * </pre>
   *
   * <code>string subject = 1;</code>
   * @return The bytes for subject.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectBytes() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subject_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object eventType_;
  /**
   * <pre>
   * The event type. (E.g., "login", "Login Successful", "Login Failed")
   * </pre>
   *
   * <code>string event_type = 2;</code>
   * @return The eventType.
   */
  @java.lang.Override
  public java.lang.String getEventType() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The event type. (E.g., "login", "Login Successful", "Login Failed")
   * </pre>
   *
   * <code>string event_type = 2;</code>
   * @return The bytes for eventType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_DATE_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp startDate_;
  /**
   * <pre>
   * The start date for filtering
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_date = 3;</code>
   * @return Whether the startDate field is set.
   */
  @java.lang.Override
  public boolean hasStartDate() {
    return startDate_ != null;
  }
  /**
   * <pre>
   * The start date for filtering
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_date = 3;</code>
   * @return The startDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getStartDate() {
    return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
  }
  /**
   * <pre>
   * The start date for filtering
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_date = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
    return getStartDate();
  }

  public static final int END_DATE_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp endDate_;
  /**
   * <pre>
   * The end date for filtering
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_date = 4;</code>
   * @return Whether the endDate field is set.
   */
  @java.lang.Override
  public boolean hasEndDate() {
    return endDate_ != null;
  }
  /**
   * <pre>
   * The end date for filtering
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_date = 4;</code>
   * @return The endDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getEndDate() {
    return endDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
  }
  /**
   * <pre>
   * The end date for filtering
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_date = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder() {
    return getEndDate();
  }

  public static final int SOURCE_FIELD_NUMBER = 5;
  private volatile java.lang.Object source_;
  /**
   * <pre>
   * Ip address of the machine
   * </pre>
   *
   * <code>string source = 5;</code>
   * @return The source.
   */
  @java.lang.Override
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Ip address of the machine
   * </pre>
   *
   * <code>string source = 5;</code>
   * @return The bytes for source.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subject_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subject_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventType_);
    }
    if (startDate_ != null) {
      output.writeMessage(3, getStartDate());
    }
    if (endDate_ != null) {
      output.writeMessage(4, getEndDate());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(source_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, source_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subject_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subject_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventType_);
    }
    if (startDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStartDate());
    }
    if (endDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getEndDate());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(source_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, source_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters)) {
      return super.equals(obj);
    }
    com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters other = (com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters) obj;

    if (!getSubject()
        .equals(other.getSubject())) return false;
    if (!getEventType()
        .equals(other.getEventType())) return false;
    if (hasStartDate() != other.hasStartDate()) return false;
    if (hasStartDate()) {
      if (!getStartDate()
          .equals(other.getStartDate())) return false;
    }
    if (hasEndDate() != other.hasEndDate()) return false;
    if (hasEndDate()) {
      if (!getEndDate()
          .equals(other.getEndDate())) return false;
    }
    if (!getSource()
        .equals(other.getSource())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getSubject().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    if (hasStartDate()) {
      hash = (37 * hash) + START_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
    }
    if (hasEndDate()) {
      hash = (37 * hash) + END_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndDate().hashCode();
    }
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code audit.v1.Filters}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:audit.v1.Filters)
      com.gridcsp.adelson.sdk.audit.protobuf.v1.FiltersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gridcsp.adelson.sdk.audit.protobuf.v1.AuditProto.internal_static_audit_v1_Filters_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gridcsp.adelson.sdk.audit.protobuf.v1.AuditProto.internal_static_audit_v1_Filters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters.class, com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters.Builder.class);
    }

    // Construct using com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      subject_ = "";

      eventType_ = "";

      if (startDateBuilder_ == null) {
        startDate_ = null;
      } else {
        startDate_ = null;
        startDateBuilder_ = null;
      }
      if (endDateBuilder_ == null) {
        endDate_ = null;
      } else {
        endDate_ = null;
        endDateBuilder_ = null;
      }
      source_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gridcsp.adelson.sdk.audit.protobuf.v1.AuditProto.internal_static_audit_v1_Filters_descriptor;
    }

    @java.lang.Override
    public com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters getDefaultInstanceForType() {
      return com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters.getDefaultInstance();
    }

    @java.lang.Override
    public com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters build() {
      com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters buildPartial() {
      com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters result = new com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters(this);
      result.subject_ = subject_;
      result.eventType_ = eventType_;
      if (startDateBuilder_ == null) {
        result.startDate_ = startDate_;
      } else {
        result.startDate_ = startDateBuilder_.build();
      }
      if (endDateBuilder_ == null) {
        result.endDate_ = endDate_;
      } else {
        result.endDate_ = endDateBuilder_.build();
      }
      result.source_ = source_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters) {
        return mergeFrom((com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters other) {
      if (other == com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters.getDefaultInstance()) return this;
      if (!other.getSubject().isEmpty()) {
        subject_ = other.subject_;
        onChanged();
      }
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        onChanged();
      }
      if (other.hasStartDate()) {
        mergeStartDate(other.getStartDate());
      }
      if (other.hasEndDate()) {
        mergeEndDate(other.getEndDate());
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object subject_ = "";
    /**
     * <pre>
     * The subject (user or service) who did an action in the system
     * </pre>
     *
     * <code>string subject = 1;</code>
     * @return The subject.
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The subject (user or service) who did an action in the system
     * </pre>
     *
     * <code>string subject = 1;</code>
     * @return The bytes for subject.
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The subject (user or service) who did an action in the system
     * </pre>
     *
     * <code>string subject = 1;</code>
     * @param value The subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubject(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subject_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The subject (user or service) who did an action in the system
     * </pre>
     *
     * <code>string subject = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubject() {
      
      subject_ = getDefaultInstance().getSubject();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The subject (user or service) who did an action in the system
     * </pre>
     *
     * <code>string subject = 1;</code>
     * @param value The bytes for subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subject_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object eventType_ = "";
    /**
     * <pre>
     * The event type. (E.g., "login", "Login Successful", "Login Failed")
     * </pre>
     *
     * <code>string event_type = 2;</code>
     * @return The eventType.
     */
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The event type. (E.g., "login", "Login Successful", "Login Failed")
     * </pre>
     *
     * <code>string event_type = 2;</code>
     * @return The bytes for eventType.
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The event type. (E.g., "login", "Login Successful", "Login Failed")
     * </pre>
     *
     * <code>string event_type = 2;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The event type. (E.g., "login", "Login Successful", "Login Failed")
     * </pre>
     *
     * <code>string event_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      
      eventType_ = getDefaultInstance().getEventType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The event type. (E.g., "login", "Login Successful", "Login Failed")
     * </pre>
     *
     * <code>string event_type = 2;</code>
     * @param value The bytes for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventType_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp startDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startDateBuilder_;
    /**
     * <pre>
     * The start date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_date = 3;</code>
     * @return Whether the startDate field is set.
     */
    public boolean hasStartDate() {
      return startDateBuilder_ != null || startDate_ != null;
    }
    /**
     * <pre>
     * The start date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_date = 3;</code>
     * @return The startDate.
     */
    public com.google.protobuf.Timestamp getStartDate() {
      if (startDateBuilder_ == null) {
        return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
      } else {
        return startDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The start date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_date = 3;</code>
     */
    public Builder setStartDate(com.google.protobuf.Timestamp value) {
      if (startDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startDate_ = value;
        onChanged();
      } else {
        startDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The start date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_date = 3;</code>
     */
    public Builder setStartDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (startDateBuilder_ == null) {
        startDate_ = builderForValue.build();
        onChanged();
      } else {
        startDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The start date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_date = 3;</code>
     */
    public Builder mergeStartDate(com.google.protobuf.Timestamp value) {
      if (startDateBuilder_ == null) {
        if (startDate_ != null) {
          startDate_ =
            com.google.protobuf.Timestamp.newBuilder(startDate_).mergeFrom(value).buildPartial();
        } else {
          startDate_ = value;
        }
        onChanged();
      } else {
        startDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The start date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_date = 3;</code>
     */
    public Builder clearStartDate() {
      if (startDateBuilder_ == null) {
        startDate_ = null;
        onChanged();
      } else {
        startDate_ = null;
        startDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The start date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_date = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getStartDateBuilder() {
      
      onChanged();
      return getStartDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The start date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_date = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
      if (startDateBuilder_ != null) {
        return startDateBuilder_.getMessageOrBuilder();
      } else {
        return startDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
      }
    }
    /**
     * <pre>
     * The start date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_date = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getStartDateFieldBuilder() {
      if (startDateBuilder_ == null) {
        startDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getStartDate(),
                getParentForChildren(),
                isClean());
        startDate_ = null;
      }
      return startDateBuilder_;
    }

    private com.google.protobuf.Timestamp endDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endDateBuilder_;
    /**
     * <pre>
     * The end date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_date = 4;</code>
     * @return Whether the endDate field is set.
     */
    public boolean hasEndDate() {
      return endDateBuilder_ != null || endDate_ != null;
    }
    /**
     * <pre>
     * The end date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_date = 4;</code>
     * @return The endDate.
     */
    public com.google.protobuf.Timestamp getEndDate() {
      if (endDateBuilder_ == null) {
        return endDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
      } else {
        return endDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The end date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_date = 4;</code>
     */
    public Builder setEndDate(com.google.protobuf.Timestamp value) {
      if (endDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endDate_ = value;
        onChanged();
      } else {
        endDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The end date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_date = 4;</code>
     */
    public Builder setEndDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (endDateBuilder_ == null) {
        endDate_ = builderForValue.build();
        onChanged();
      } else {
        endDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The end date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_date = 4;</code>
     */
    public Builder mergeEndDate(com.google.protobuf.Timestamp value) {
      if (endDateBuilder_ == null) {
        if (endDate_ != null) {
          endDate_ =
            com.google.protobuf.Timestamp.newBuilder(endDate_).mergeFrom(value).buildPartial();
        } else {
          endDate_ = value;
        }
        onChanged();
      } else {
        endDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The end date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_date = 4;</code>
     */
    public Builder clearEndDate() {
      if (endDateBuilder_ == null) {
        endDate_ = null;
        onChanged();
      } else {
        endDate_ = null;
        endDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The end date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_date = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getEndDateBuilder() {
      
      onChanged();
      return getEndDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The end date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_date = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder() {
      if (endDateBuilder_ != null) {
        return endDateBuilder_.getMessageOrBuilder();
      } else {
        return endDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
      }
    }
    /**
     * <pre>
     * The end date for filtering
     * </pre>
     *
     * <code>.google.protobuf.Timestamp end_date = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getEndDateFieldBuilder() {
      if (endDateBuilder_ == null) {
        endDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getEndDate(),
                getParentForChildren(),
                isClean());
        endDate_ = null;
      }
      return endDateBuilder_;
    }

    private java.lang.Object source_ = "";
    /**
     * <pre>
     * Ip address of the machine
     * </pre>
     *
     * <code>string source = 5;</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Ip address of the machine
     * </pre>
     *
     * <code>string source = 5;</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Ip address of the machine
     * </pre>
     *
     * <code>string source = 5;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ip address of the machine
     * </pre>
     *
     * <code>string source = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      
      source_ = getDefaultInstance().getSource();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ip address of the machine
     * </pre>
     *
     * <code>string source = 5;</code>
     * @param value The bytes for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      source_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:audit.v1.Filters)
  }

  // @@protoc_insertion_point(class_scope:audit.v1.Filters)
  private static final com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters();
  }

  public static com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Filters>
      PARSER = new com.google.protobuf.AbstractParser<Filters>() {
    @java.lang.Override
    public Filters parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Filters(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Filters> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Filters> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

