// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audit.proto

package com.gridcsp.adelson.sdk.audit.protobuf.v1;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:audit.v1.SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. A filter that chooses which audit records are returned.
   * </pre>
   *
   * <code>.audit.v1.Filters filter = 1;</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <pre>
   * Optional. A filter that chooses which audit records are returned.
   * </pre>
   *
   * <code>.audit.v1.Filters filter = 1;</code>
   * @return The filter.
   */
  com.gridcsp.adelson.sdk.audit.protobuf.v1.Filters getFilter();
  /**
   * <pre>
   * Optional. A filter that chooses which audit records are returned.
   * </pre>
   *
   * <code>.audit.v1.Filters filter = 1;</code>
   */
  com.gridcsp.adelson.sdk.audit.protobuf.v1.FiltersOrBuilder getFilterOrBuilder();

  /**
   * <pre>
   * Optional. The maximum number of results to return from this request. Default is 25.
   * </pre>
   *
   * <code>int32 page_size = 2;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * Optional. E.g., reverse chronological order of event_time
   * </pre>
   *
   * <code>string order_by = 3;</code>
   * @return The orderBy.
   */
  java.lang.String getOrderBy();
  /**
   * <pre>
   * Optional. E.g., reverse chronological order of event_time
   * </pre>
   *
   * <code>string order_by = 3;</code>
   * @return The bytes for orderBy.
   */
  com.google.protobuf.ByteString
      getOrderByBytes();

  /**
   * <pre>
   * Optional. If present, then retrieve the next batch of results from the preceding call
   * to this request.
   * </pre>
   *
   * <code>string page_token = 4;</code>
   * @return The pageToken.
   */
  java.lang.String getPageToken();
  /**
   * <pre>
   * Optional. If present, then retrieve the next batch of results from the preceding call
   * to this request.
   * </pre>
   *
   * <code>string page_token = 4;</code>
   * @return The bytes for pageToken.
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();
}
