// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audit.proto

package com.gridcsp.adelson.sdk.audit.protobuf.v1;

public interface SearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:audit.v1.SearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of audit records.
   * </pre>
   *
   * <code>repeated .audit.v1.AuditRecord audit_records = 1;</code>
   */
  java.util.List<com.gridcsp.adelson.sdk.audit.protobuf.v1.AuditRecord> 
      getAuditRecordsList();
  /**
   * <pre>
   * A list of audit records.
   * </pre>
   *
   * <code>repeated .audit.v1.AuditRecord audit_records = 1;</code>
   */
  com.gridcsp.adelson.sdk.audit.protobuf.v1.AuditRecord getAuditRecords(int index);
  /**
   * <pre>
   * A list of audit records.
   * </pre>
   *
   * <code>repeated .audit.v1.AuditRecord audit_records = 1;</code>
   */
  int getAuditRecordsCount();
  /**
   * <pre>
   * A list of audit records.
   * </pre>
   *
   * <code>repeated .audit.v1.AuditRecord audit_records = 1;</code>
   */
  java.util.List<? extends com.gridcsp.adelson.sdk.audit.protobuf.v1.AuditRecordOrBuilder> 
      getAuditRecordsOrBuilderList();
  /**
   * <pre>
   * A list of audit records.
   * </pre>
   *
   * <code>repeated .audit.v1.AuditRecord audit_records = 1;</code>
   */
  com.gridcsp.adelson.sdk.audit.protobuf.v1.AuditRecordOrBuilder getAuditRecordsOrBuilder(
      int index);

  /**
   * <pre>
   * Optional. If there might be more results than those appearing in this response, then
   * `nextPageToken` is included.  To get the next set of results, call this
   * method again using the value of `nextPageToken` as `pageToken`.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * Optional. If there might be more results than those appearing in this response, then
   * `nextPageToken` is included.  To get the next set of results, call this
   * method again using the value of `nextPageToken` as `pageToken`.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
